### ISSUE TITLE
"textBlock" doesn't seem to work in blockTypeHandlers

### ISSUE THREAD

**Issue by kmelve** [sanity-io/block-content-to-react#1]
I try to overwrite and add a class to the paragraph-element with this code:

```jsx
<BlockContent
  blockTypeHandlers={{
    textBlock: {
      p: ({ children = [] }) => <p className="lede">{children}</p>,
    },
  }}
  blocks={text}
/>
``` 

But it only returns the default `<p>...</p>` syntax. I've tried several variations, with and without parameter destructuring.

**Comment by rexxars** [comment]
Sorry about that. The API *will* get better soon, but in the meantime you can override the paragraph handler with `normal` instead of `p` in there.
