### ISSUE TITLE
When encountering unknown types and no serializer for that type exists, the component crashes

### ISSUE THREAD

**Issue by saasen** [sanity-io/block-content-to-react#10]
# Versions
```
@sanity/block-content-to-react    2.0.1
react                             16.3.2
```

# Issue

When the `BlockContent` encounters an unknown type defined in Sanity, the component crashes and effectively crashes the page. I don't know if this applies to marks and annotations as well.

It would be nice to have some way of telling the component to ignore unknown fields, and for several reasons:
* When introducing new fields in an `array-of-block` field, it's very handy to deploy this beforehand in production and prepare all content before deploying frontend(s) to handle the new content.
* When working in a dev-environment you are also effectively crashing other developers application when introducing new types in the `array-of-block` field. One workaround here is to work on a separate document, but you get the idea.

You could potentially add a switch for this in the component. I guess it would be up to you to decide if you should make this behaviour default as well. As we've already discussed, one could use the `__DEV__` to define the behaviour, but then you would still encounter problems when working on a multi-developer setup as you would be breaking the other developers documents.

**Comment by skogsmaskin** [comment]
Bumping this!

**Comment by microbit-matt-hillsdon** [comment]
I think it would be great to allow for a fallback component when faced with unknown content. Then the developer can chose to throw an error, render nothing or render a placeholder of their choosing (perhaps like the studio unknown field placeholders).

We've found this to be more painful than expected when working in a team to collaborating on different components needed for a page.

**Comment by limitlessloop** [comment]
I'm using `block-content-to-markdown` and as a workaround, I'm recreating the code required for the frontend. In most cases this is possible and most of the time it's just a replica of the preview used in Sanity Studio. This was working fine until I needed to alter the values entered into Sanity Studio. Now I have to do the same string manipulation in the serializer as I haven't found a way to save values from the preview component to output as the data for that block type.

Here's an example of the serializer type:
```js
const serializers = {
	types: {
		codesandbox: props => `<div class="wide"><iframe
	src="https://codesandbox.io/embed/${props.node.container}?autoresize=1&fontsize=14&hidenavigation=1&module=%2Fstyles.css&theme=${props.node.theme}&view=${props.node.view}"
	style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
	title="zealous-fast-c2dng"
	allow="geolocation; microphone; camera; midi; vr; accelerometer; gyroscope; payment; ambient-light-sensor; encrypted-media; usb"
	sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"
  ></iframe></div>`
	}
}
```

And example of the block type:

```js
import React from "react";

const CodeSandboxPreview = ({ value }) => {
  const { url = "test", theme = "light", view = "split", container } = value;
  const splitURL = url.split("/");
  // [ 'https:', '', 'codesandbox.io', 's', 'zealous-fast-c2dng' ]
  const [, , , , containerName] = splitURL;
  container = containerNAme // Update value of container not possible as read only
  console.log(value.container)
  const embedUrl = `https://codesandbox.io/embed/${container}?autoresize=1&fontsize=14&hidenavigation=1&module=%2Fstyles.css&theme=${theme}&view=${view}`;
  return (
    <iframe
      src={embedUrl}
      style={{ width: '100%', height: '500px', border: 0, borderRadius: '4px', overflow: 'hidden' }}
      title={container}
      allow="geolocation; microphone; camera; midi; vr; accelerometer; gyroscope; payment; ambient-light-sensor; encrypted-media; usb"
      sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"
    />
  );

};

export default {
  name: "codesandbox",
  type: "object",
  title: "CodeSandbox Embed",
  preview: {
    select: {
      url: "url",
      theme: "theme",
      view: "view",
      container: "container"
    },
    component: CodeSandboxPreview
  },
  fields: [
    {
      name: "url",
      type: "url",
      title: "CodeSandbox URL"
    },
    {
      name: "container",
      title: "Container",
      hidden: true,
      type: "string"
    },
    {
      name: "theme",
      title: "Theme",
      type: "string",
      options: {
        list: [
          { title: 'Light', value: 'light' },
          { title: 'Dark', value: 'dark' }
        ],
        layout: 'dropdown'
      }
    },
    {
      name: "view",
      title: "View",
      type: "string",
      options: {
        list: [
          { title: 'Editor + Preview', value: 'split' },
          { title: 'Preview', value: 'preview' },
          { title: 'Editor', value: 'editor' }
        ],
        layout: 'dropdown'
      }
    }
  ]
};
```

**Comment by rexxars** [comment]
Check out the new `@portabletext/react` module - by default it will print a warning the console when encountering unknown types (and render a hidden DOM element for easier discovery). It also allows you to disable the warnings, and even override the component used when no component is registered for it:

https://github.com/portabletext/react-portabletext
