### ISSUE TITLE
Is there a way to just return from a serializer?

### ISSUE THREAD

**Issue by vongohren** [sanity-io/block-content-to-react#19]
I have a case where I want to serialze a special style inside the block type. But I want to return default rendering of all other styles. I dont want to have to write the serializer for all styles inside the block

How can I do this?

**Comment by bjoerge** [comment]
Hi @vongohren. It's possible to delegate to `BlockContent.defaultSerializers`:

Check out this test for an example:
https://github.com/sanity-io/block-content-to-react/blob/a41894874c0ca7b7aa06e6ac3fa143cdd950c657/test/dom/BlockContent.test.js#L60-L70

**Comment by vongohren** [comment]
Cool, thank you :D
