### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by fandy** [sanity-io/block-content-to-react#26]
Would be great to get Enums for block types, like in Contentful. Also, typings for the props of the render nodes would be useful.

**Comment by balazsorban44** [comment]
To anyone interested, I created a gist very fast. It is not complete, but a starting point. I plan to expand it as I go along:

https://gist.github.com/balazsorban44/fd6b5accd5c8c6449bdb6a63f6fa124e

**Comment by nclarx** [comment]
Thanks @balazsorban44 this is just what I was looking for, I'll see about opening a PR if I can contribute anything useful!

**Comment by GHesericsu** [comment]
Thank you @balazsorban44. That worked perfectly.

**Comment by simonpeters** [comment]
This really should be added to the repo it self

**Comment by rexxars** [comment]
Check out the new `@portabletext/react` module with full typescript support!

https://github.com/portabletext/react-portabletext

**Comment by nclarx** [comment]
amazing, thanks @rexxars, the new lib looks great

**Comment by pixelknitter** [comment]
@rexxars any plans to support PortableText in React Native?

**Comment by ShayNehmad-RecoLabs** [comment]
Any chance of getting react16 support on `@portabletext/react`?

**Comment by rexxars** [comment]
> @rexxars any plans to support PortableText in React Native?

There is an experimental renderer for it, yes: https://github.com/portabletext/react-native-portabletext

**Comment by rexxars** [comment]
> Any chance of getting react16 support on `@portabletext/react`?

No, probably not. The library is built with hooks.
This library should still work though, even if typings aren't available.
