### ISSUE TITLE
highlight not working

### ISSUE THREAD

**Issue by a-ditucalan** [sanity-io/block-content-to-react#27]
i add some customization in my sanity portable text. i just want to show the highlighted text but in my  web project it did not show highlighted but the em and strong tag is working in portable text

**Comment by bslipek** [comment]
Here is a manual how to makes highlighted text works: https://www.sanity.io/docs/customization#decorators-e6401a8fe843

**Comment by AzadKshitij** [comment]
How can I use this highlighted text to show in my frontend?

**Comment by rexxars** [comment]
Closing this, as the new `@portabletext/react` library is the successor to this module.
Please see https://github.com/portabletext/react-portabletext
