### ISSUE TITLE
Change default value of `renderContainerOnSingleChild` to `true`

### ISSUE THREAD

**Issue by barbogast** [sanity-io/block-content-to-react#30]
I was very confused / surprised by the renderer not rendering my configured `container` all of a sudden. It took me a while to realise that the reason was that the block content only contained one element. I also nearly missed the option `renderContainerOnSingleChild`.

To have differing element hierarchies between content with one element and with multiple elements seems to be a special requirement rather then a good default. I suggest therefore to change the default of `renderContainerOnSingleChild` to `true`.

It would be a breaking change, though :-/

Thanks for considering :-)

**Comment by rexxars** [comment]
Closing this, as the new `@portabletext/react` library is the successor to this module.
Please see https://github.com/portabletext/react-portabletext
