### ISSUE TITLE
Feature request: Override react-native styles 

### ISSUE THREAD

**Issue by ricokahler** [sanity-io/block-content-to-react#38]
I apologize if I missed something, but reading through the code, I don't see anything that lets me override the text styles for `react-native`.

I know it's possible to completely replace the element used during serialization but that's not exactly what I want. The default serializers are good! I just need to update the font.

Let me know if you're accepting PRs or thoughts. Would love to get a good solution in here is possible. Thanks for making it work in react-native in the first place!

**Comment by rajikaimal** [comment]
Wrap in a div and change style?

**Comment by rexxars** [comment]
Closing this as https://github.com/portabletext/react-native-portabletext is now the successor library to this one
