### ISSUE TITLE
BlockContent component tries to render a link using the key property as the mark name

### ISSUE THREAD

**Issue by vonba** [sanity-io/block-content-to-react#46]
I am pulling content to Gatsby from Sanity using GraphQL. Content arrives without issues and I can use inline images, header tags, block quotes etc. However, when a block contains a link, I get the following error:

```
Unknown mark type "68344811ed4b", please specify a serializer for it in the `serializers.marks` prop 
    at SpanSerializer (http://localhost:8000/commons.js:10953:29)
```
"68344811ed4b" corresponds to the key of the link.

This is the content I am passing to the BlockContent component:

```
content: Array(1)
0:
  children: Array(2)
    0: {_key: "48b95fb74a12", _type: "span", marks: Array(1), text: "Here is the link"}
    1: {_key: "4ac794989d8d", _type: "span", marks: Array(0), text: ""}
  length: 2
  __proto__: Array(0)
  markDefs: Array(2)
    0: {_key: "a02fe6d7d7ca", _type: "link"}
    1: {_key: "68344811ed4b", _type: "link", href: "http://exmple.com"}
  length: 2
  __proto__: Array(0)
  style: "normal"
  _key: "9cb5d7dcd417"
  _type: "block"
```

If I create a custom serializer with the name of the key (serializers.marks.68344811ed4b) this gets passed an item of type span. This seems to be true for any link in any Sanity document.

I am using v 2.0.7 of @sanity/block-content-to-react.

**Comment by rexxars** [comment]
Closing this, as the new `@portabletext/react` library is the successor to this module.
Please see https://github.com/portabletext/react-portabletext
