### ISSUE TITLE
Can't create list in sanity

### ISSUE THREAD

**Issue by BrkatiDzo** [sanity-io/block-content-to-react#48]
I can't get list items from the editor/schema

--mySchema
export default {
  title: "Block Content",
  name: "blockContent",
  type: "array",
  of: [
    {
      title: "Block",
      type: "block",
      // Styles let you set what your user can mark up blocks with. These
      // correspond with HTML tags, but you can set any title or value
      // you want and decide how you want to deal with it where you want to
      // use your content.
      styles: [
        { title: "Normal", value: "normal" },
        { title: "H1", value: "h1" },
        { title: "H2", value: "h2" },
        { title: "H3", value: "h3" },
        { title: "H4", value: "h4" },
        { title: "Quote", value: "blockquote" },
      ],
      lists: [
        { title: "Bullet", value: "bullet" },
        { title: "Numbered", value: "number" }
      ],
      // Marks let you mark up inline text in the block editor.
      marks: {
        // Decorators usually describe a single property – e.g. a typographic
        // preference or highlighting by editors.
        decorators: [
          { title: "Strong", value: "strong" },
          { title: "Emphasis", value: "em" },
        ],
        // Annotations can be any object structure – e.g. a link or a footnote.
        annotations: [
          {
            title: "URL",
            name: "link",
            type: "object",
            fields: [
              {
                title: "URL",
                name: "href",
                type: "url",
              },
            ],
          },
        ],
      },
    },
    // You can add additional types here. Note that you can't use
    // primitive types such as 'string' and 'number' in the same array
    // as a block type.
    {
      type: "image",
      options: { hotspot: true },
    },
  ],
};

editor
<img width="772" alt="Screenshot 2021-06-15 at 17 47 21" src="https://user-images.githubusercontent.com/22876227/122093860-c9c49d80-ce0b-11eb-8f83-6b95b4eb4f30.png">

response
<img width="554" alt="Screenshot 2021-06-15 at 17 46 49" src="https://user-images.githubusercontent.com/22876227/122093949-de089a80-ce0b-11eb-9386-67738324a189.png">

tried with a lot of variations of serializer like here:
https://github.com/sanity-io/block-content-to-react/issues/29
https://github.com/sanity-io/block-content-to-react/issues/33

but it just doesn't read the list items.

**Comment by miguelangelchancahum** [comment]
Hi @BrkatiDzo I hope you area akoay, I would like know if you have a solution to this issue, I have the same problem.

**Comment by davincios** [comment]
Super frustrating that it doesn't read list items. Is there any work around?
