### ISSUE TITLE
How to render empty <p></p> as linebreak?

### ISSUE THREAD

**Issue by ceruberu** [sanity-io/block-content-to-react#53]
I'm using empty lines for better readability

<img width="687" alt="스크린샷 2021-09-22 오후 10 58 53" src="https://user-images.githubusercontent.com/21168032/134357820-9550e560-c084-4c27-91c6-aa684c994c1d.png">

<img width="293" alt="스크린샷 2021-09-22 오후 11 00 00" src="https://user-images.githubusercontent.com/21168032/134357935-f08f1629-9469-4433-86ca-da95fe8a911f.png">

These empty lines are ignored.

<img width="519" alt="스크린샷 2021-09-22 오후 11 01 33" src="https://user-images.githubusercontent.com/21168032/134358193-b869689b-862c-42e4-bef4-494a0a72d62f.png">

I tried using \n / empty space / and &nbsp;

I guess the serializer just renders them as strings

**Comment by ceruberu** [comment]
I guess this was just CSS issue with tailwind, closing

**Comment by fuhrthom** [comment]
Please post your solution for this problem.

**Comment by trevorfehrman** [comment]
If it's the same issue I just had a Tailwind reset was zero-ing out the margin on all `<p>` tags.  I just added this to my globals.css file (I'm using Next)

```
.rich-text-container p {
  margin-bottom: 1rem;
}
```
