### ISSUE TITLE
How can i use Katex?

### ISSUE THREAD

**Issue by thebosph** [sanity-io/block-content-to-react#55]
Hello everyone. I try to using Sanity Latex Input. Sanity studio ok but in frontend(nextjs) i cant show latex content with @sanity/block-content-to-react. How can i do this?

Error: Unknown block type "latex", please specify a serializer for it in the `serializers.types` prop.
and 

Unknown block type "undefined", please specify a serializer for it in the `serializers.types` prop

how can i serialize Latex? 

thanks a lot.

**Comment by runeb** [comment]
Here is an example

A component for rendering katex content:

https://github.com/sanity-io/sanity-template-kitchen-sink/blob/main/template/web/src/components/Latex.js

And registering it as a type in the serializer

https://github.com/sanity-io/sanity-template-kitchen-sink/blob/497290e200af2daa67f61cd7c7f3f71f5f0edb73/template/web/src/components/serializers.js#L24

**Comment by rexxars** [comment]
Closing this, as the new `@portabletext/react` library is the successor to this module.
Please see https://github.com/portabletext/react-portabletext
